server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/microservico
    username: postgres
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        type: trace
    show-sql: true
